---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openai-api-key
  namespace: default
spec:
  encryptedData:
    OPENAI_API_KEY: AgAlXQLVEfW6aigBQwDlzZHpUe8CfIGe7PVamWXRwKhOQONrJTflrHoSWSIJUAxR1P3uzBX/5f7tcBT2uCNvYqgZAUuA91Z1Bchs2ylFa4bkCxZb9tU6wVRiMNTDTHOHRisdHVV225oJSVBHStNDqH/DHEuCcjd+PEh1XROEbQBRblaGm+ra7m2nGGF4u+vhqoVU4Z/T+TaiNHMW3dckmPNEx64uHc2KwuhlozF5Vkn8zO/XZCQzlBZ8xOy0zHsj9XQaqYraPRN/lKlHZBSD96W7tycRq5Z76f7dFlG62eMDfFHrPUGln/pxjF1x7CqR3TPKa21xTyaEGUagKumhpUPYFEumHpvqNo2L0XbDqFTBsUwD0WB0Mr+91/Zzej2hNReVl+cAGF4cFiA4P9W39tfNHEDfDLVooQNI4D9tGvpw9u+wSNL4rkGLu3IDWoMrpPjQliGrpTnhhT5LZOzUW/T6XOHyt/OWoyMhYt8CmASu7Wl2+v86xHbQMF+H+qPR0Iy6MApZU1+CXaiYhgq/b7DSjmTGFGmn9R7DDOdX71Ey3GRYOEESAyFDwOobchII8hAL/1Zidu4Mna+t666Gtk2ENvMbnWV5mU+wyQFhMiJK639dZitYhRnaEU09LPZy97OYVcfbA2CmFmlSTxb0rbdsfyay2mQcyejeLnlBsD1Kr+V9l0zf+ymu5aYl8/DWhO/Xg8N13BXl5Lmp+Zzq1myXD4yga5AfECw+3+n8ors9eM4pWGvIqNEnXY2a71AWN1aX4BTep+sLrQELPkTUQE77fm5X5Kz19wsyg4GJpOduCZ0pNY6OftWPnuqHyky8YD8AzHtNxYQ/KmAiB9hMkJpdvKUo1dwegCD5RaVnxWBnLm/Y4ipyZ/GzcrZMx0rZh//rUShWQIHGsJg1k1rX0cLfyl6nsw==
  template:
    metadata:
      creationTimestamp: null
      name: openai-api-key
      namespace: default
    type: Opaque
