apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-webui-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/open-webui  # Replace with the desired path on your machine
